version: "3.8"

services:
  router:
    container_name: router
    image: ghcr.io/connext/nxtp-router:$ROUTER_VERSION
    restart: always
    ports:
      - $ROUTER_EXTERNAL_PORT:8080
    volumes:
      - ./config.json:/home/node/router/config.json
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - nxtp

  ################################################################################

  logdna:
    container_name: logdna
    image: logdna/logspout:v1.2.0
    restart: always
    environment:
      LOGDNA_KEY: $LOGDNA_KEY
      TAGS: $LOGDNA_TAG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - nxtp


  #  alertmanager-discord:
  #    container_name: alertmanager-discord
  #    image: benjojo/alertmanager-discord
  #    restart: always
  #    environment:
  #      DISCORD_WEBHOOK: $DISCORD_WEBHOOK
  #    logging:
  #      driver: json-file
  #      options:
  #          max-size: 10m
  #    networks:
  #      - nxtp


networks:
  nxtp:
